// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Navigation() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"py-3 w-full\"><div class=\"container mx-auto flex justify-between\"><a href=\"/\" class=\"relative w-8 h-8\"><img src=\"assets/favicon_light/android-chrome-512x512.png\" alt=\"Light Logo\" class=\"absolute inset-0 w-full h-full object-contain\" x-show=\"theme === &#39;dark&#39;\"> <img src=\"assets/favicon_dark/android-chrome-512x512.png\" alt=\"Dark Logo\" class=\"absolute inset-0 w-full h-full object-contain\" x-show=\"theme === &#39;light&#39;\"></a><div class=\"flex gap-4 items-center\"><a href=\"https://github.com/Sourjaya/converse\" target=\"_blank\"><img src=\"assets/favicon_github_light/favicon.ico\" alt=\"Light Logo\" width=\"24\" height=\"24\" x-show=\"theme === &#39;dark&#39;\"> <img src=\"assets/favicon_github_dark/favicon.ico\" alt=\"Dark Logo\" width=\"24\" height=\"24\" x-show=\"theme === &#39;light&#39;\"></a><div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ThemeSwitcher().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
